import type { NextPage } from "next";
import Head from "next/head";
import Masthead from "../components/masthead";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Masthead />
		</>
	);
};

export default Home;
