import type { NextPage } from "next";
import Head from "next/head";
import AboutMe from "../components/aboutme";
import Masthead from "../components/masthead";
import Offer from "../components/offer";
import TrustedBy from "../components/trustedby";
import Works from "../components/works";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Masthead />
			<AboutMe />
			<Offer />
			<Works />
			<TrustedBy />
		</>
	);
};

export default Home;
